# Define os serviços (contentores) que compõem a aplicação
services:
  # Serviço do backend
  backend:
    # Constrói a imagem a partir do Dockerfile localizado na pasta ./backend
    build: ./backend
    # Define uma política de reinício para o contentor
    restart: unless-stopped
    # Mapeia a porta 5000 do contentor para a porta 5000 da máquina anfitriã
    ports:
      - "5000:5000"
    # Define um volume para persistir APENAS o ficheiro do banco de dados.
    # Isto garante que os seus dados não sejam perdidos.
    volumes:
      - db-data:/usr/src/app/agendamentos.db

  # Serviço do frontend
  frontend:
    # Constrói a imagem a partir do Dockerfile localizado na pasta ./frontend
    build: ./frontend
    # Define uma política de reinício para o contentor
    restart: unless-stopped
    # Mapeia a porta 80 do contentor para a porta 80 da máquina anfitriã
    ports:
      - "8089:80"
    # Garante que o serviço de backend seja iniciado antes do frontend
    depends_on:
      - backend

# Declara os volumes nomeados para persistência de dados
volumes:
  db-data:
